# Generated by Django 2.2.12 on 2020-07-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
    ]
